# Mail configuration example
# Use environment variables for real values
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:zhang_d@sunseer.co.jp}
spring.mail.password=${MAIL_PASSWORD:ntfk mhby jpro fgvr}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

