spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sunlunch
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  upload:
    base-dir: uploads
    max-image-size-bytes: 5242880

menu:
  sync:
    url: https://www.tamagoya.co.jp/menu_list/smartmeal/
    auto-enabled: false
